### ISSUE TITLE
Build Vocab

### ISSUE THREAD

**Issue by AldawsariNLP** [explosion/spacy-stanfordnlp#1]
Great work. So what about building the vocabulary at least word vectors for these languages ? 
Thanks

**Comment by AldawsariNLP** [comment]
I meant building word vectors for more languages in spaCy.

**Comment by ines** [comment]
It's pretty easy to add your own vectors and create a vectors model for any language currently supported by spaCy. See here for details: https://spacy.io/usage/vectors-similarity#converting
