### ISSUE TITLE
Access CoreNLP parsing tree

### ISSUE THREAD

**Issue by lcswillems** [explosion/spacy-stanfordnlp#13]
Hi,
Is it possible to access CoreNLP parsing tree from the `doc` object? Not only dependencies.
Thank you,
Lucas Willems

**Comment by ines** [comment]
What do you mean by the "CoreNLP parsing tree"? The constituency parse? 

This wrapper is currently only intended for the new StanfordNLP models, not the CoreNLP server. It makes all linguistic annotations available that are also supported by spaCy. If you want to use CoreNLP, it's probably easiest to just call into it directly.

**Comment by lcswillems** [comment]
Yes you are right. It is what I did. Thank you
