### ISSUE TITLE
How do use the NER stanfordnlp annotator?

### ISSUE THREAD

**Issue by askhogan** [explosion/spacy-stanfordnlp#16]
Using this wrapper, you'll be able to use the following annotations, computed by your pretrained stanfordnlp model:

Statistical tokenization (reflected in the Doc and its tokens)
Lemmatization (token.lemma and token.lemma_)
Part-of-speech tagging (token.tag, token.tag_, token.pos, token.pos_)
Dependency parsing (token.dep, token.dep_, token.head)
Sentence segmentation (doc.sents)

Where is Named Entity Recognition? https://stanfordnlp.github.io/CoreNLP/ner.html

Also SpaCy's own website says specifically state of the art comes with CORENLP not SpaCy

https://cl.ly/285a4edaf7a5/Image%202019-06-06%20at%207.32.06%20PM.png

This is not a post to whine - this is a post to say I want to get work done - I want to use a tool like prodigy - but everytime I spend an hour or so of additional dev time and the SpaCy models give me junk entities and then this package shows up within evolution as a potential bridge - yet it lacks the most essential annotator. Thats my point.

**Comment by honnibal** [comment]
> Where is Named Entity Recognition? https://stanfordnlp.github.io/CoreNLP/ner.html

Well...There's currently no NER predictions from StanfordNLP models, and so this package does not provide any NER predictions. You appear to be confusing StanfordNLP and Stanford CoreNLP (not our names). From https://stanfordnlp.github.io/ : 

> Stanford CoreNLP is our Java toolkit which provides a wide variety of NLP tools.

> StanfordNLP is a new Python project which includes a neural NLP pipeline and an interface for working with Stanford CoreNLP in Python.

Eventually the StanfordNLP models will support NER...The CoreNLP models are quite old, and not really actively maintained. They also require you to run GPL Java software. Stanford's current neural models are the ones we refer to when we say that their package has "the latest state of the art".

Also:

> this is a post to say I want to get work done - I want to use a tool like prodigy - but everytime I spend an hour or so of additional dev time and the SpaCy models give me junk entities and then this package shows up within evolution as a potential bridge - yet it lacks the most essential annotator. Thats my point.

Come on. Have a word with yourself mate.

**Comment by askhogan** [comment]
@hannival thanks for the explanation and you are correct I was confusing the two - 

As to the end - I would rather solve this factually than using conjecture like you did prior to closing the ticket

I came on here to ask two questions to a company that sells a tool Prodigy to customers. You are paid by said company. I want to use your tools. I am giving my experience wherein the SpaCY models give very bad results for NER out of the box. Perhaps my docs are not SpaCY's speciality. But CoreNLP and StanfordNER as old as they are blew SpaCY out of the water in terms of accurately categorizing text for Organization, Person, and Dollar amount. I am more than happy to share my files and results - which is much more scientific than the opinions you give here such as

 "so much older" "our stuff is so good - have a talk with yourself mate"  - results are results and these are what I got.

**Comment by askhogan** [comment]
Updating ticket after analysis 

1. The StanfordNLP NER does do a better job out of the gate - but upon more analysis that is because they use many more phrase pattern matching rule under places like `edu/stanford/nlp/models/kbp/regexner_caseless.tab` 

2. When these are added to Spacy - Spacy performs better

3. After spending time with Spacy - it is much more customizable and easier to work with. Very quickly your results will become better than StanfordNER
