### ISSUE TITLE
install requirements

### ISSUE THREAD

**Issue by mehmetilker** [explosion/spacy-stanfordnlp#17]
I see there "stanfordnlp>=0.1.0,<0.2.1" line in requirement.txt but still getting following error.

ERROR: spacy-stanfordnlp 0.1.2 has requirement stanfordnlp<0.2.0,>=0.1.0, but you'll have stanfordnlp 0.2.0 which is incompatible.

I guess there is a problem in last release.

**Comment by ines** [comment]
Looks like we forgot to update the dependency in the `setup.py`. Fixing this, thanks! Since the version is compatible, you should still be able to just install the more recent `stanfordnlp` on top of `spacy-stanfordnlp`.
