### ISSUE TITLE
Including stanza support?

### ISSUE THREAD

**Issue by BramVanroy** [explosion/spacy-stanfordnlp#25]
Stanfordnlp did a version bump of their repository and has renamed it to [`stanza`](https://github.com/stanfordnlp/stanza/). Are there any plans to make a spacy-stanza, or update this repository to include stanza support? I don't think their API has changed too much.

**Comment by ines** [comment]
Yes, see here: https://github.com/explosion/spacy-stanfordnlp/tree/feature-stanza

**Comment by BramVanroy** [comment]
Damn son, that was quick!
