### ISSUE TITLE
Stuck for Greek and Hebrew examples

### ISSUE THREAD

**Issue by hammad26** [explosion/spacy-stanfordnlp#4]
I am using following code to get results on Greek and Hebrew language. It is giving no results, look like that it is stuck on these inputs.

**Greek**
```
snlp = stanfordnlp.Pipeline(lang="el")
nlp = StanfordNLPLanguage(snlp)
doc = nlp("συνεπεια στο ραντεβου")
```

**Hebrew**
```
snlp = stanfordnlp.Pipeline(lang="he")
nlp = StanfordNLPLanguage(snlp)
doc = nlp("השירות")
```

Can you tell why it is happening? How can I avoid from this?

**Comment by ines** [comment]
Thanks for the report – I'll need to test this! Just to confirm: Are you on the latest version of `spacy-stanfordnlp`? If not, the problem might be related to #2, which should already be fixed.

**Comment by hammad26** [comment]
My bad, on older version. Let me check on latest one.

**Comment by hammad26** [comment]
Yes, fixed on latest version. Thanks for the quick reply.
And sorry for this I am using 2 environments, 1st one was having latest libs(did initial testing on it) but 2nd one was having old libs(doing rigorous testing on it).

**Comment by ines** [comment]
@hammad26 Thanks for updating and glad this fixed it! (And no worries, using separate environments is always a good thing, at least in my opinion 👍 )
