### ISSUE TITLE
Matcher result problem

### ISSUE THREAD

**Issue by mehmetilker** [explosion/spacy-stanfordnlp#5]
I have successfully run parser and see pos/dependency result same as with stanfordnlp.
But when I run Matcher over tokens I see unexpected matchs.
For example I should get only PROPN+ tokens but I see verb matches as well.
And empty match...

I have gone through following code here but I could not see something related with Matcher.
https://github.com/explosion/spacy-stanfordnlp/blob/master/spacy_stanfordnlp/language.py

BTW, default installation comes with spacy-nightly 6a and I have tried with 9a as well. 

```python
import stanfordnlp
from spacy_stanfordnlp import StanfordNLPLanguage
from spacy.matcher import Matcher
import csv

config = {
    'processors': 'tokenize,pos,lemma', #mwt, depparse
	'lang': 'en', # Language code for the language to build the Pipeline in
}

snlp = stanfordnlp.Pipeline(**config)
nlp = StanfordNLPLanguage(snlp)

matcher = Matcher(nlp.vocab)
matcher.add("ProperNounRule", None, *[
	# [{'POS': 'PROPN'}, {'POS': 'PROPN'}, {'POS': 'PROPN'}],
	# [{'POS': 'PROPN'}, {'POS': 'PROPN'}]
	[{'POS': 'PROPN', 'OP': '+'}]
	# {'POS': 'NOUN', 'OP': '+'}
])

text = "US was among the first countries to recognise opposition leader Juan Guaido as legitimate leader, arguing President Nicholas Maduro's May 2018 re-election was a sham. Maduro accuses Guaido of being a coup-mongering puppet for US President Trump."

text = text.replace("“", "\"").replace("”", "\"").replace("’", "'")
doc = nlp(text)

matches = matcher(doc)
print('\n>>> Match result')
for (match_id, start, end) in matches:
	label = doc.vocab.strings[match_id]	
	span = doc[start:end]	
	print(label, ":", str(span), ">", start, ":", end)	

```

Bolds are expected result. 
```
**ProperNounRule : US > 0 : 1**
**ProperNounRule : Juan > 10 : 11**
**ProperNounRule : Juan Guaido > 10 : 12**
ProperNounRule : as > 11 : 12
**ProperNounRule : Nicholas > 17 : 18**
**ProperNounRule : Nicholas Maduro > 17 : 19**
ProperNounRule : 's > 18 : 19
**ProperNounRule : Nicholas Maduro's May > 17 : 20**
ProperNounRule : 2018 re-election > 18 : 20
ProperNounRule : was > 19 : 20
ProperNounRule : sham > 21 : 22
ProperNounRule : a > 28 : 29
ProperNounRule : - > 30 : 31
ProperNounRule :  > 39 : 40
ProperNounRule :  > 39 : 41
```

**Comment by ines** [comment]
Thanks for the report! This is very mysterious and there's definitely something up here. But I just tried your exact code and I can't reproduce this 🤔

I'm getting the following results:

```
ProperNounRule : US > 0 : 1
ProperNounRule : Juan > 10 : 11
ProperNounRule : Juan Guaido > 10 : 12
ProperNounRule : Guaido > 11 : 12
ProperNounRule : President > 17 : 18
ProperNounRule : President Nicholas > 17 : 19
ProperNounRule : Nicholas > 18 : 19
ProperNounRule : President Nicholas Maduro > 17 : 20
ProperNounRule : Nicholas Maduro > 18 : 20
ProperNounRule : Maduro > 19 : 20
ProperNounRule : May > 21 : 22
ProperNounRule : Maduro > 28 : 29
ProperNounRule : Guaido > 30 : 31
ProperNounRule : US > 39 : 40
ProperNounRule : US President > 39 : 41
ProperNounRule : President > 40 : 41
ProperNounRule : US President Trump > 39 : 42
ProperNounRule : President Trump > 40 : 42
ProperNounRule : Trump > 41 : 42
```

I tried it with both versions of StanfordNLP and both nightlies. I also tried it in the current stable spaCy version (where the operators and quantifiers implementation is different and inconsistent). But even in that scenario, I get correct matches – just fewer.

**Comment by mehmetilker** [comment]
I do not have installed any model? Should I install ?

I will try with 2.0.18 again.

```
===================== Installed models (spaCy v2.1.0a9) =====================
spaCy installation: C:\py-spacy\_env368_2\lib\site-packages\spacy

No models found in your current environment.
```

(_env368_2) C:\_Dev\_dev\temp\py-spacy>pip list
Package                  Version
------------------------ -----------
appdirs                  1.4.3
astroid                  2.1.0
autopep8                 1.4.3
blis                     0.2.2
boto                     2.49.0
boto3                    1.9.97
botocore                 1.12.97
bz2file                  0.98
cachetools               3.1.0
certifi                  2018.11.29
chardet                  3.0.4
Click                    7.0
colorama                 0.4.1
ConceptNet               5.6.4
ConfigArgParse           0.14.0
conllu                   1.2.2
cymem                    2.0.2
datrie                   0.7.1
docutils                 0.14
ftfy                     5.5.1
gensim                   3.7.1
gitdb2                   2.0.5
GitPython                2.1.11
google-api-python-client 1.7.8
google-auth              1.6.3
google-auth-httplib2     0.0.3
httplib2                 0.12.1
idna                     2.8
isort                    4.3.4
jmespath                 0.9.3
jsonschema               2.6.0
langcodes                1.4.1
lazy-object-proxy        1.3.1
marisa-trie              0.7.5
mccabe                   0.6.1
msgpack                  0.6.1
msgpack-python           0.5.6
murmurhash               1.0.1
nltk                     3.4
numpy                    1.16.1
ordered-set              3.1
pandas                   0.24.1
Pillow                   5.4.1
pip                      19.0.3
plac                     0.9.6
preshed                  2.0.1
protobuf                 3.6.1
psycopg2-binary          2.7.7
pyasn1                   0.4.5
pyasn1-modules           0.2.4
pycodestyle              2.5.0
pylint                   2.2.2
python-dateutil          2.8.0
pytz                     2018.9
PyYAML                   3.13
ratelimiter              1.2.0.post0
regex                    2018.1.10
requests                 2.21.0
rope                     0.12.0
rsa                      4.0
s3transfer               0.2.0
scikit-learn             0.20.2
scipy                    1.2.1
setuptools               40.6.2
singledispatch           3.4.0.3
six                      1.12.0
sklearn                  0.0
smart-open               1.8.0
smmap2                   2.0.5
snakemake                5.4.2
**spacy-nightly            2.1.0a9
spacy-stanfordnlp        0.0.3**
srsly                    0.0.5
**stanfordnlp              0.1.2**
thinc                    7.0.2
thinc-gpu-ops            0.0.4
**torch                    1.0.1**
torchvision              0.2.1
tqdm                     4.31.1
typed-ast                1.3.1
uritemplate              3.0.0
urllib3                  1.24.1
wasabi                   0.0.15
wcwidth                  0.1.7
wordfreq                 2.2.1
wrapt                    1.10.11
xmltodict                0.11.0

**Comment by mehmetilker** [comment]
My mistake. Sorry for confusion.

I was trying to merge match results but I have removed the merge code while pasting here for clearity.

Apparently match result is changing while merging spans. I will try to find a way to properly merge tokens..

```python
matches = matcher(doc)
print('\n>>> Match result')
for (match_id, start, end) in matches:
	label = doc.vocab.strings[match_id]	
	span = doc[start:end]	
	print(label, ":", str(span), ">", start, ":", end)	
	#span.merge()
	if end-start > 1:
		lemmas = [t.lemma_ for t in span]
		lemmas_text = "_".join(lemmas)
		with doc.retokenize() as retokenizer:
			retokenizer.merge(span, attrs={'LEMMA': lemmas_text})
```

**Comment by ines** [comment]
@mehmetilker The new `retokenizer` API is really optimised for bulk merging and will then take care of aligning the merges automatically (unlike the old `span.merge`, which made this difficult). So ideally, you want to be collecting your spans first and then merge them all at once.

Something like this should work:

```python
spans_to_merge = []
for match_id, start, end in matches:
	span = doc[start:end]	
	if end - start > 1:
        spans_to_merge.append(span)

with doc.retokenize() as retokenizer:
    for span in spans_to_merge:
        lemmas = [t.lemma_ for t in span]
        lemmas_text = "_".join(lemmas)
        retokenizer.merge(span, attrs={'LEMMA': lemmas_text})
```

**Comment by mehmetilker** [comment]
Great. Thank you for example.
